#1.spring boot项目中同时存在application.properties和application.yml文件时，两个文件都有效，但是application.properties的优先级会比application.yml高
#2.优先级 /config/application.properties
#          -> /application.properties
#               -> /src/main/resource/config/application.properties
#                    -> /src/main/resource/application.properties

#端口
server:
  port: 8001


#启用调试日志
#debug: true

#开发配置
spring:
  profiles:
    #可以配置若干个配置文件，用spring.profiles.active激活--dev. test.
    active: dev

  #数据源
  datasource:
    url: jdbc:mysql://47.100.213.205:3306/test?&useSSL=false
    username: root
    password: Mydb6.

  banner:
    location: classpath:static/banner/banner.txt


#公共配置与profiles选择无关
mybatis:
  #定义别名
  typeAliasesPackage: com.darkbright.demo.domain.entity
  #如果Mapper.xml与Mapper.class在同一个包下且同名，spring扫描Mapper.class的同时会自动扫描同名的Mapper.xml并装配到Mapper.class。
  #如果Mapper.xml与Mapper.class不在同一个包下或者不同名，就必须使用配置mapperLocations指定mapper.xml的位置。
  #此时spring是通过识别mapper.xml中的 <mapper namespace="com.fan.mapper.UserDao"> namespace的值来确定对应的Mapper.class的。
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    cacheEnabled: false


